### ISSUE TITLE
Issue max items stored as user favourites

### ISSUE THREAD

**Issue by luukverhoeven** [MFreakNL/moodle-block-user_favorites#3]
Hi Luuk,
We have found that the number of favourites that can be stored are limited because the mdl_user_preferences.value is set to type varchar(1333) in the Moodle database. Obviously we can change this to text, but I wanted to check if this is just an issue with our database (running on MariaDB). Do you have any advice on this? Thanks Ken

**Comment by luukverhoeven** [comment]
Converting the column "mdl_user_preferences .value" to text is the best solution for now.

**Comment by luukverhoeven** [comment]
I will improve the plugin by storing this information in a separate table and implement a privacy provider for it.

**Comment by KenFarr** [comment]
Thanks for adding this.
Ken

**Comment by KenFarr** [comment]
We have found another problem in that of /lib/moodlelib.php throws a coding error as it contains a limit on the size of data stored in that field  
$value =   (string)$value;
if (core_text::strlen($value) > 1333) 

If this line is adjusted then the plugin works perfectly, but clearly a separate table is needed.
Ken
--

**Comment by luukverhoeven** [comment]
Hi Ken, 

There is a new release in the [development](https://github.com/MFreakNL/moodle-block-user_favorites/tree/development) branch. Can you validate if this is working as expected?

Changes:
- Saving user favourites to a separate table.
- Convert (existing) data, when upgrading plugin `user_preference` -> `block_user_favorites`
- Implement privacy provider for the new table.

This should solve this issue.
